id = "vapor-theme"
name = "Vapor Theme"
description = "A theme inspired on Vapor Theme from Steam Deck"
version = "0.0.1"
schema_version = 1
authors = ["felipetesc"]
repository = "https://github.com/felipetesc/zed-vapor"
