id = "zed-vapor"
name = "Zed Vapor Theme"
description = "A theme inspired on Vapor Thme for Steam Deck"
version = "0.0.1"
schema_version = 1
authors = ["felipetesc"]
repository = "https://github.com/felipetesc/zed-vapor"
